In [2408]:
pdf_path = r'F:\Welltime.ltd\Compass-UDAS\Statement 23-24\Sch issued on 1st Nov 23 will pd 1st Dec 23\3954630008.pdf'

In [2409]:
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    for page_num, text in enumerate(extracted_text, start=1):
        print(f"Page {page_num}:")
        print(text.strip())
        print("\n---\n")

Page 1:
Contract Monthly Pay Statement
Ashiq Ghauri and Sarfraz Ghauri t/a Ghauri Dental Centre
Ghauri Dental Centre
3 Wormholt Road
Shepherds Bush
London
W12 0LUCONTRACT
QRV   3954630008
ASHIQ GHAURI AND SARFRAZ GHAURI T/A
GHAURI DENTAL CENTRE
If you have any queries please call the NHS
Dental Services Helpdesk on 0300 330 1348 or
email nhsbsa.dentalservices@nhsbsa.nhs.uk
105357
1

---

Page 2:
NATIONAL HEALTH SERVICE
 Contract QRV   3954630008
Statement Reference  2324/07  ASHIQ GHAURI AND SARFRAZ
GHAURI T/A GHAURI DENTAL
CENTRE

Date  01/11/23 VAT No. 654434729
PAY STATEMENT
Non Contributory Items Payments Deductions
Total Contract Value £14,561.72
ZZ Mandatory Services - pre April 2017 £14,561.72
Monthly Pay £1,568.74
ZZ Mandatory Services - pre April 2017 £1,568.74
Non-Superannuable Deductions
Statutory Levy England £3.13
Contract £2.27
105483 BAGHERI £0.10
107884 HAQ £0.10
638943 A PATEL £0.55
101949 ZAMAN £0.11
Performers' Net Pensionable Earnings £69.38
105483 BAGHERI £23.00
651133 S GHAURI £0.08
107884 HAQ £22.14
101949 ZAMAN £24.16
Performers' Superannuation Contribution £7.39
105483 BAGHERI @ 9.80% £2.26
651133 S GHAURI @ 5.10% £0.01
107884 HAQ @ 12.50% £2.76
101949 ZAMAN @ 9.80% £2.36
Patients' Charges £516.00
105483 BAGHERI £232.20
880590 SW HAIDER £232.20
101949 ZAMAN £51.60
Remissions £335.40
105483 BAGHERI £103.20
880590 SW HAIDER £180.60
101949 ZAMAN £51.60
Exemptions
105483 BAGHERI £77.40
880590 SW HAIDER £25.80
101949 ZAMAN £0.00
Employer's Contribution (for information) £9.98
Performer   105483 BAGHERI @ 14.38% £3.31
Performer   651133 S GHAURI @ 14.38% £0.01
Performer   107884 HAQ @ 14.38% £3.19
Performer   101949 ZAMAN @ 14.38% £3.47
Performers' Net Pensionable Earnings Equivalent (for information) £120.85
880590 SW HAIDER £0.08
638943 A PATEL £120.77
SUB TOTALS £1,904.14 £526.52
TOTAL NET PAY £1,377.62

OTHER FINANCIAL ACTIVITY DURING THE PERIOD
Description Receipts Payments Deductions
Note that receipts will not appear above until the payment has been cleared

THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES
2

---

Page 3:
NATIONAL HEALTH SERVICE
 Contract QRV   3954630008
Statement Reference  2324/07  ASHIQ GHAURI AND SARFRAZ
GHAURI T/A GHAURI DENTAL
CENTRE

Date  01/11/23 VAT No. 654434729
ACTIVITY STATEMENT
Activity for October (21/09/2023 - 19/10/2023)
Contracted Units of Dental Activity 2023/24 1.00
Contracted Units of Dental Activity 2022/23 1.00
Units of Dental Activity for this Month
Current Financial Year 2023/24 27.60
Last Financial Year 2022/23 0.00
Other Financial Years 0.00
Cumulative Units for Dental Activity
Current Financial Year 2023/24 167.20
Last Financial Year 2022/23 180.40
Units of Dental Activity per Performer
105483 BAGHERI
Current Financial Year 2023/24 14.40
Last Financial Year 2022/23 0.00
Other Financial Years 0.00
880590 SW HAIDER
Current Financial Year 2023/24 10.80
Last Financial Year 2022/23 0.00
Other Financial Years 0.00
101949 ZAMAN
Current Financial Year 2023/24 2.40
Last Financial Year 2022/23 0.00
Other Financial Years 0.00

THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES
3

---

Page 4:
NATIONAL HEALTH SERVICE
 Contract QRV   3954630008
Statement Reference  2324/07  ASHIQ GHAURI AND SARFRAZ
GHAURI T/A GHAURI DENTAL
CENTRE

Date  01/11/23 VAT No. 654434729
PROVIDER SUMMARY (CURRENT FINANCIAL YEAR)
UNITS OF DENTAL ACTIVITY INFORMATION (ALL PERFORMERS)
Band Forms Weighting No of Units
1 Child 0 0.00 0.00
1 Adult 0 0.00 0.00
2 (pre 25/11/22) Child 0 0.00 0.00
2 (pre 25/11/22) Adult 0 0.00 0.00
2(a) Child 0 0.00 0.00
2(a) Adult 0 0.00 0.00
2(b) Child 0 0.00 0.00
2(b) Adult 0 0.00 0.00
2(c) Child 0 0.00 0.00
2(c) Adult 0 0.00 0.00
3 Child 0 0.00 0.00
3 Adult 0 0.00 0.00
1 * Child 2 1.20 2.40 * = Urgent Treatment
1 * Adult 21 1.20 25.20
Advice Only 0 0.00 0.00
Triage 0 0.00 0.00
Reg11 Child 0 0.00 0.00
Reg11 Adult 0 0.00 0.00
Prescriptions Issued 0 0.00 0.00 Dom. Services 0
Denture Repairs 0 0.00 0.00 Sedation Services 0
Bridge Repairs 0 0.00 0.00 Further Treatment 0
Removal of Sutures 0 0.00 0.00 Incomplete Trmt 0
Arrest of Bleeding 0 0.00 0.00 Guaranteed Trmt 0
Late Submitted Forms 1
No of Deletions 0
General Units Total this Month 27.60 (excluding 1.20 submitted late)
Deletion Units 0.00
Net General Units 27.60
Orthodontic Treatment
Case Assessment Only 0 0.00 0.00 Ortho Abandoned 0
Assess and Accept 0 0.00 0.00 Ortho Discontinued 0
Appliance Fitted-Child<10 0 0.00 0.00 Ortho Completed 0
Appliance Fitted-Child>9 0 0.00 0.00
Appliance Fitted-Adult 0 0.00 0.00
Repairs to Appliances 0 0.00 0.00
No of Deletions 0 Ortho Reg 11 0
Ortho Units Total this Month 0.00
Deletion Units 0.00
Net Ortho Units 0.00
PATIENTS CHARGE TOTALS (ALL PERFORMERS)
Total Patient Charges £516.00
Remission Amount Total £335.40 Remission Cases 13
Exemption Amount Total (£103.20) Exemption Cases 4
Total to be deducted from contract value £180.60
4

---

# Date, VAT No and Statement Reference

# Statement Reference

In [2410]:
import re
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_statement_references_from_text(extracted_text):
    statement_references = []
    for text in extracted_text:
        statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
        if statement_reference_match:
            statement_reference = statement_reference_match.group(1)
            statement_references.append(statement_reference)
    return statement_references

if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf'  # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    statement_references = extract_statement_references_from_text(extracted_text)
    
    print("Extracted Statement References:")
    for statement_reference in statement_references:
        print(statement_reference)

Extracted Statement References:
2324/07
2324/07
2324/07

In [2411]:
import re
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_statement_references_from_text(extracted_text):
    statement_reference = None  # Initialize statement reference variable
    for text in extracted_text:
        if statement_reference is None:  # Check if statement reference is not assigned yet
            statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
            if statement_reference_match:
                statement_reference = statement_reference_match.group(1)
                break  # Break loop after finding the first statement reference
    return statement_reference

if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf'  # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    statement_reference = extract_statement_references_from_text(extracted_text)
    
    if statement_reference:
        print("Extracted Statement Reference:", statement_reference)
    else:
        print("No Statement Reference found in the PDF.")

Extracted Statement Reference: 2324/07

In [2412]:
statement_reference

'2324/07'

# VAT Number

In [2413]:
import re
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_vat_numbers_from_text(extracted_text):
    vat_numbers = set()  # Using a set to store unique VAT numbers
    for text in extracted_text:
        vat_number_matches = re.findall(r'VAT\s*No\.\s*(\d+)', text)
        vat_numbers.update(vat_number_matches)
    return vat_numbers

if __name__ == "__main__":
    #pdf_path = 'Att8820166.pdf'  # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    vat_numbers = extract_vat_numbers_from_text(extracted_text)
    
    print("Extracted VAT Numbers:")
    for vat_number in vat_numbers:
        print(vat_number)

Extracted VAT Numbers:
654434729

# Contract Monthly Pay Statement

In [2414]:
# code for the complete Contract Monthly Pay Statement text on this page
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
            # Check if the text "Contract Monthly Pay Statement" is in the extracted text
            if "Contract Monthly Pay Statement" in text:
                break  # Stop extracting text from further pages
    return text_per_page

if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    found_text = False  # Flag to check if the desired text is found
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_text:
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output
        elif "Contract Monthly Pay Statement" in text:
            found_text = True  # Set the flag to True when the desired text is found
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output
    print(contract_monthly_pay_statement_text)

Contract Monthly Pay Statement
Ashiq Ghauri and Sarfraz Ghauri t/a Ghauri Dental Centre
Ghauri Dental Centre
3 Wormholt Road
Shepherds Bush
London
W12 0LUCONTRACT
QRV   3954630008
ASHIQ GHAURI AND SARFRAZ GHAURI T/A
GHAURI DENTAL CENTRE
If you have any queries please call the NHS
Dental Services Helpdesk on 0300 330 1348 or
email nhsbsa.dentalservices@nhsbsa.nhs.uk
105357
1
---

In [2415]:
if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract += text.strip() + "\n"
        elif "CONTRACT" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("CONTRACT") + len("CONTRACT")
            end_index = text.find("If ")
            # Append the text between these indices
            contract += text[start_index:end_index].strip() + "\n"
    print("CONTRACT: ")
    print(contract)

CONTRACT:
QRV   3954630008
ASHIQ GHAURI AND SARFRAZ GHAURI T/A
GHAURI DENTAL CENTRE

# Address

In [2416]:
if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract_monthly_pay_statement_text += text.strip() + "\n"
        elif "Contract Monthly Pay Statement" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("Contract Monthly Pay Statement") + len("Contract Monthly Pay Statement")
            end_index = text.find("CONTRACT")
            # Append the text between these indices
            contract_monthly_pay_statement_text += text[start_index:end_index].strip() + "\n"
    print(contract_monthly_pay_statement_text)

Ashiq Ghauri and Sarfraz Ghauri t/a Ghauri Dental Centre
Ghauri Dental Centre
3 Wormholt Road
Shepherds Bush
London
W12 0LU

In [2417]:
if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract_monthly_pay_statement_text += text.strip() + "\n"
        elif "Contract Monthly Pay Statement" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("Contract Monthly Pay Statement") + len("Contract Monthly Pay Statement")
            end_index = text.find("CONTRACT")
            # Append the text between these indices
            contract_monthly_pay_statement_text += text[start_index:end_index].strip() + "\n"
    
    # Splitting the text into Contract Name and Address
    parts = contract_monthly_pay_statement_text.split('\n', 1)
    Contract_Name = parts[0]
    Address = parts[1] if len(parts) > 1 else ""
    
    print("Contract Name:", Contract_Name)
    print("Address:", Address)

Contract Name: Ashiq Ghauri and Sarfraz Ghauri t/a Ghauri Dental Centre
Address: Ghauri Dental Centre
3 Wormholt Road
Shepherds Bush
London
W12 0LU

# Contract_Name

In [2418]:
if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract_monthly_pay_statement_text += text.strip() + "\n"
        elif "Contract Monthly Pay Statement" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("Contract Monthly Pay Statement") + len("Contract Monthly Pay Statement")
            end_index = text.find("CONTRACT")
            # Append the text between these indices
            contract_monthly_pay_statement_text += text[start_index:end_index].strip() + "\n"
    
    # Extracting Contract Name
    Contract_Name = contract_monthly_pay_statement_text.split('\n', 1)[0]
    
    print("Contract Name:", Contract_Name)

Contract Name: Ashiq Ghauri and Sarfraz Ghauri t/a Ghauri Dental Centre

# Address

In [2419]:
if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract_monthly_pay_statement_text += text.strip() + "\n"
        elif "Contract Monthly Pay Statement" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("Contract Monthly Pay Statement") + len("Contract Monthly Pay Statement")
            end_index = text.find("CONTRACT")
            # Append the text between these indices
            contract_monthly_pay_statement_text += text[start_index:end_index].strip() + "\n"
    
    # Extracting Address
    parts = contract_monthly_pay_statement_text.split('\n', 1)
    Address = parts[1] if len(parts) > 1 else ""
    
    print("Address:", Address)

Address: Ghauri Dental Centre
3 Wormholt Road
Shepherds Bush
London
W12 0LU

# Contract

In [2420]:
if __name__ == "__main__":
    #pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract += text.strip() + "\n"
        elif "CONTRACT" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("CONTRACT") + len("CONTRACT")
            end_index = text.find("If ")
            # Append the text between these indices
            contract += text[start_index:end_index].strip() + "\n"
    print("CONTRACT: ")
    print(contract)

CONTRACT:
QRV   3954630008
ASHIQ GHAURI AND SARFRAZ GHAURI T/A
GHAURI DENTAL CENTRE

In [2421]:
# Splitting the contract string into Contract_ID and Contract_Name
contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

# Assuming the first part is Contract_ID and the second part is Contract_Name
Contract_ID = contract_lines[0].strip()
Contract_Name = contract_lines[1].strip()
# Printing the results
print("Contract_ID:", Contract_ID)
print("Contract_Name:", Contract_Name)

Contract_ID: QRV   3954630008
Contract_Name: ASHIQ GHAURI AND SARFRAZ GHAURI T/A
GHAURI DENTAL CENTRE

In [2422]:
import pandas as pd
# Splitting the contract string into Contract_ID and Contract_Name
contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

# Assuming the first part is Contract_ID and the second part is Contract_Name
Contract_ID = contract_lines[0].strip()
Contract_Name = contract_lines[1].strip()
df = pd.DataFrame({'Contract_ID': [Contract_ID], 'Contract_Name': [Contract_Name], 'Address': [Address]})
print(df)

        Contract_ID                                      Contract_Name  \
0  QRV   3954630008  ASHIQ GHAURI AND SARFRAZ GHAURI T/A\nGHAURI DE...

                                             Address
0  Ghauri Dental Centre\n3 Wormholt Road\nShepher...

In [2423]:
# Splitting the contract string into Contract_ID and Contract_Name
contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

# Assuming the first part is Contract_ID
Contract_ID = contract_lines[0].strip()

# Printing the Contract_ID
print("Contract_ID:", Contract_ID)

Contract_ID: QRV   3954630008

In [2424]:
# Splitting the contract string into Contract_ID and Contract_Name
contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

# Assuming the second part is Contract_Name
Contract_Name = contract_lines[1].strip()

# Printing the Contract_Name
print("Contract_Name:", Contract_Name)

Contract_Name: ASHIQ GHAURI AND SARFRAZ GHAURI T/A
GHAURI DENTAL CENTRE

# Contract_Details

In [2425]:
import pandas as pd
# Splitting the contract string into Contract_ID and Contract_Name
contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

# Assuming the first part is Contract_ID and the second part is Contract_Name
Contract_ID = contract_lines[0].strip()
Contract_Name = contract_lines[1].strip()
df1 = pd.DataFrame({'Contract_ID': [Contract_ID], 'Contract_Name': [Contract_Name], 'Address': [Address],'Vat_No':[vat_number]})
df1

,Contract_ID,Contract_Name,Address,Vat_No
0,QRV 3954630008,ASHIQ GHAURI AND SARFRAZ GHAURI T/A\nGHAURI DE...,Ghauri Dental Centre\n3 Wormholt Road\nShepher...,654434729

In [2426]:
df1

,Contract_ID,Contract_Name,Address,Vat_No
0,QRV 3954630008,ASHIQ GHAURI AND SARFRAZ GHAURI T/A\nGHAURI DE...,Ghauri Dental Centre\n3 Wormholt Road\nShepher...,654434729

In [2427]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('compass.db')
c = conn.cursor()

# Create Contracts_Details table
c.execute('''CREATE TABLE Contracts_Details
             (ID INTEGER PRIMARY KEY AUTOINCREMENT,
              Contract_ID TEXT,
              Contract_Name TEXT,
              Address TEXT,
              VAT_No TEXT)''')

# Save (commit) the changes
conn.commit()

# Close the connection
conn.close()

OperationalError: table Contracts_Details already exists

In [2428]:
import pandas as pd
import sqlite3

# Assuming you have a DataFrame named df1

# Connect to SQLite database
conn = sqlite3.connect('compass.db')

# Assuming your table name is 'your_table_name'
table_name = 'Contracts_Details'

# Insert DataFrame records into SQLite database
df1.to_sql(table_name, conn, if_exists='append', index=False)

# Commit changes and close connection
conn.commit()
conn.close()

# Performers' Superannuation Contribution

In [2429]:
import re
import pandas as pd

def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None

def format_table(table_text, contract):
    # Extracting rows using regular expression
    rows = re.findall(r'(\d+)\s+([A-Z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', table_text)

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Performer_ID": row[0],
            "Name": row[1],
            "Percentage": row[2],
            "Amount (£)": row[3],
            "Contract_ID": contract  # Add Contract_ID to each row
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

if __name__ == "__main__":
    pdf_path = 'BSA Statement 01 Highlighted.pdf' # Change this to the path of your PDF file
    #contract_file_path = 'BSA Statement 01 Highlighted.pdf'  # Path to the file containing contract information
    # Splitting the contract string into Contract_ID and Contract_Name
    contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

    # Assuming the first part is Contract_ID
    Contract_ID = contract_lines[0].strip()

    

    contract = Contract_ID

    extracted_text = extract_text_from_pdf(pdf_path)

    # Concatenate all the extracted text into a single string
    complete_pdf_text = "\n".join(extracted_text)

    # Extract the text of the Performers' Superannuation Contribution table
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)

    # Print the extracted table text
    if performers_superannuation_table_text:
        print("Performers' Superannuation Contribution Table:")
        formatted_table = format_table(performers_superannuation_table_text, contract)
        # Convert the formatted table to DataFrame
        df1 = pd.DataFrame(formatted_table)
        print(df1)
    else:
        print("Performers' Superannuation Contribution Table not found in the PDF text.")

Performers' Superannuation Contribution Table not found in the PDF text.

In [2430]:
import re
import pandas as pd
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_statement_references_from_text(extracted_text):
    statement_references = []
    for text in extracted_text:
        statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
        if statement_reference_match:
            statement_reference = statement_reference_match.group(1)
            statement_references.append(statement_reference)
    return statement_references

def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None

def format_table(table_text, contract, statement_reference):
    # Extracting rows using regular expression
    rows = re.findall(r'(\d+)\s+([A-Z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', table_text)

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Contract_ID": contract,  # Add Contract_ID to each row
            "Statement_Reference": statement_reference,  # Add Statement_Reference to each row
            "Performer_ID": row[0],
            "Name": row[1],
            "Percentage": row[2],
            "Amount ": row[3]
            #"Contract_ID": contract,  # Add Contract_ID to each row
            #"Statement_Reference": statement_reference  # Add Statement_Reference to each row
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

if __name__ == "__main__":
    pdf_path = 'BSA Statement 01 Highlighted.pdf'
    # Extract statement references from PDF
    extracted_text = extract_text_from_pdf(pdf_path)
    statement_references = extract_statement_references_from_text(extracted_text)
    
    # Choose one statement reference for the sake of example (you might need to adjust this based on your actual data)
    statement_reference = statement_references[0] if statement_references else None

    # Extract the table text
    extracted_text = extract_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(extracted_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)

    # Print the extracted table text
    if performers_superannuation_table_text:
        print("Performers' Superannuation Contribution Table:")
        formatted_table = format_table(performers_superannuation_table_text, "Q62 0000000000", statement_reference)
        # Convert the formatted table to DataFrame
        df2 = pd.DataFrame(formatted_table)
        print(df2)
    else:
        print("Performers' Superannuation Contribution Table not found in the PDF text.")

Performers' Superannuation Contribution Table:
      Contract_ID Statement_Reference Performer_ID       Name Percentage  \
0  Q62 0000000000             1819/05       704822   H CHUNG        9.30
1  Q62 0000000000             1819/05       651133  S GHAURI       13.50
2  Q62 0000000000             1819/05       973823   E KADIU       12.50

  Amount
0  115.45
1  176.33
2  446.27

In [2431]:
df2

,Contract_ID,Statement_Reference,Performer_ID,Name,Percentage,Amount
0,Q62 0000000000,1819/05,704822,H CHUNG,9.30,115.45
1,Q62 0000000000,1819/05,651133,S GHAURI,13.50,176.33
2,Q62 0000000000,1819/05,973823,E KADIU,12.50,446.27

In [2432]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('compass.db')
c = conn.cursor()

# Create Superannuation table
c.execute('''CREATE TABLE Superannuation
             (ID INTEGER PRIMARY KEY AUTOINCREMENT,
              Contract_ID TEXT,
              Statement_Reference TEXT,
              Performer_ID TEXT,
              Name TEXT,
              Percentage TEXT,
              Amount TEXT )''')

# Save (commit) the changes
conn.commit()

# Close the connection
conn.close()

In [2433]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('compass.db')
c = conn.cursor()

# Drop the Superannuation table if it exists
c.execute('''DROP TABLE IF EXISTS Superannuation''')

# Save (commit) the changes
conn.commit()

# Close the connection
conn.close()

In [2434]:
import pandas as pd
import sqlite3

# Assuming you have a DataFrame named df1

# Connect to SQLite database
conn = sqlite3.connect('compass.db')

# Assuming your table name is 'your_table_name'
table_name = 'Superannuation Table'

# Insert DataFrame records into SQLite database
df2.to_sql(table_name, conn, if_exists='append', index=False)

# Commit changes and close connection
conn.commit()
conn.close()

# Non-Superannuable Deductions Statutory Levy

In [2435]:
import re
import pandas as pd

def extract_performers_non_superannuable_deductions(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Non-Superannuable Deductions\s*Statutory Levy'
    end_pattern = r'(?:Performers\' Net Pensionable Earnings|$)'  # End pattern is either end of table or next section

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()]
        return table_text.strip()
    else:
        return None

def format_table(table_text):
    # Extracting rows using regular expression
    rows = re.findall(r'(\d+)\s+([A-Z\s]+)\s+£([\d.]+)', table_text)

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Performer_ID": row[0],
            "Performer_Name": row[1],
            "Amount": row[2]
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

if __name__ == "__main__":
    extracted_text = extract_text_from_pdf(pdf_path)

    # Concatenate all the extracted text into a single string
    complete_pdf_text = "\n".join(extracted_text)

    # Extract the text of the Performers' Non-Superannuable Deductions Statutory Levy table
    performers_non_superannuation_table_text = extract_performers_non_superannuable_deductions(complete_pdf_text)

    # Print the extracted table text
    if performers_non_superannuation_table_text:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table:")
        print(performers_non_superannuation_table_text)

        # Format the table text
        formatted_table = format_table(performers_non_superannuation_table_text)

        # Convert the formatted table to DataFrame
        df_2 = pd.DataFrame(formatted_table)

        # Print DataFrame
        print(df_2)
    else:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table not found in the PDF text.")

Performers' Non-Superannuable Deductions Statutory Levy Table:
£110.48
Contract   £7.84
111111  A BCDEFG   £11.61
222222  B CDEFGH   £11.00
333333  C DEFGHI   £25.05
444444  D EFGHI   £29.92
5555555  E FGHIJK   £25.06
  Performer_ID Performer_Name Amount
0       111111     A BCDEFG    11.61
1       222222     B CDEFGH    11.00
2       333333     C DEFGHI    25.05
3       444444      D EFGHI    29.92
4      5555555     E FGHIJK    25.06

In [2438]:
df_2

  Performer_ID Performer_Name Amount
0       111111     A BCDEFG    11.61
1       222222     B CDEFGH    11.00
2       333333     C DEFGHI    25.05
3       444444      D EFGHI    29.92
4      5555555     E FGHIJK    25.06

In [2439]:
import re
import PyPDF2
import pandas as pd

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_statement_references_from_text(extracted_text):
    statement_references = []
    for text in extracted_text:
        statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
        if statement_reference_match:
            statement_reference = statement_reference_match.group(1)
            statement_references.append(statement_reference)
    return statement_references

def extract_contract_id(pdf_text):
    contract_id_match = re.search(r'Contract ID: (\w+)', pdf_text)
    if contract_id_match:
        return contract_id_match.group(1)
    else:
        return None

def extract_performers_non_superannuable_deductions(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Non-Superannuable Deductions\s*Statutory Levy'
    end_pattern = r'(?:Performers\' Net Pensionable Earnings|$)'  # End pattern is either end of table or next section

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()]
        return table_text.strip()
    else:
        return None

def format_table(table_text, contract_id, statement_reference):
    # Extracting rows using regular expression
    rows = re.findall(r'(\d+)\s+([A-Z\s]+)\s+£([\d.]+)', table_text)

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Contract_ID": Contract_ID,
            "Statement_Reference": statement_reference,
            "Performer_ID": row[0],
            "Performer_Name": row[1],
            "Amount": row[2]
            
            
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

if __name__ == "__main__":
    # Extract statement references from PDF
    extracted_text = extract_text_from_pdf(pdf_path)
    statement_references = extract_statement_references_from_text(extracted_text)

    # Choose one statement reference for the sake of example (you might need to adjust this based on your actual data)
    statement_reference = statement_references[0] if statement_references else None

    # Extract contract ID from the PDF
    contract_id = extract_contract_id("\n".join(extracted_text))

    # Extract the table text
    #pdf_path = 'BSA Statement 01 Highlighted.pdf'  # Change this to the path of your PDF file
    #extracted_text = extract_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(extracted_text)
    performers_non_superannuation_table_text = extract_performers_non_superannuable_deductions(complete_pdf_text)

    # Print the extracted table text
    if performers_non_superannuation_table_text:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table:")
        print(performers_non_superannuation_table_text)

        # Format the table text
        formatted_table = format_table(performers_non_superannuation_table_text, contract_id, statement_reference)

        # Convert the formatted table to DataFrame
        df_3 = pd.DataFrame(formatted_table)

        # Print DataFrame
        print(df_3)
    else:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table not found in the PDF text.")

Performers' Non-Superannuable Deductions Statutory Levy Table:
£110.48
Contract   £7.84
111111  A BCDEFG   £11.61
222222  B CDEFGH   £11.00
333333  C DEFGHI   £25.05
444444  D EFGHI   £29.92
5555555  E FGHIJK   £25.06
        Contract_ID Statement_Reference Performer_ID Performer_Name Amount
0  QRV   3954630008             1819/05       111111     A BCDEFG    11.61
1  QRV   3954630008             1819/05       222222     B CDEFGH    11.00
2  QRV   3954630008             1819/05       333333     C DEFGHI    25.05
3  QRV   3954630008             1819/05       444444      D EFGHI    29.92
4  QRV   3954630008             1819/05      5555555     E FGHIJK    25.06

In [2440]:
df_3

        Contract_ID Statement_Reference Performer_ID Performer_Name Amount
0  QRV   3954630008             1819/05       111111     A BCDEFG    11.61
1  QRV   3954630008             1819/05       222222     B CDEFGH    11.00
2  QRV   3954630008             1819/05       333333     C DEFGHI    25.05
3  QRV   3954630008             1819/05       444444      D EFGHI    29.92
4  QRV   3954630008             1819/05      5555555     E FGHIJK    25.06

In [2441]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('compass.db')
c = conn.cursor()

# Create Non-Superannuable Deductions Statutory Levy table
c.execute('''CREATE TABLE Non_Superannuable_Deductions_Statutory_Levy
             (ID INTEGER PRIMARY KEY AUTOINCREMENT,
              Contract_ID TEXT,
              Statement_Reference TEXT,
              Performer_ID TEXT,
              Performer_Name TEXT,
              Amount REAL)''')

# Save (commit) the changes
conn.commit()

# Close the connection
conn.close()

OperationalError: table Non_Superannuable_Deductions_Statutory_Levy already exists

In [2442]:
import pandas as pd
import sqlite3

# Assuming you have a DataFrame named df1

# Connect to SQLite database
conn = sqlite3.connect('compass.db')

# Assuming your table name is 'your_table_name'
table_name = 'Non_Superannuable_Deductions_Statutory_Levy'

# Insert DataFrame records into SQLite database
df_3.to_sql(table_name, conn, if_exists='append', index=False)

# Commit changes and close connection
conn.commit()
conn.close()

# Units of Dental Activity per Performer

In [2443]:
import sqlite3

# Connect to the database (or create it if it doesn't exist)
conn = sqlite3.connect('compass.db')
c = conn.cursor()

# Create table
c.execute('''CREATE TABLE Units_of_Dental_Activity_per_Performer
             (ID INTEGER PRIMARY KEY AUTOINCREMENT,
              Contract_ID TEXT,
              Statement_Reference TEXT,
              Performer_ID TEXT,
              Name TEXT,
              Current_Financial_Year TEXT,
              Current_Financial_Year_Amount REAL,
              Last_Financial_Year TEXT,
              Last_Financial_Year_Amount REAL,
              Other_Financial_Years TEXT,
              Other_Financial_Year_Amount REAL)''')

# Save (commit) the changes
conn.commit()

# Close the connection
conn.close()

OperationalError: table Units_of_Dental_Activity_per_Performer already exists

In [2444]:
import PyPDF2
import re

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_units_of_dental_activity(text_per_page):
    start_pattern = "Units of Dental Activity per Performer"
    end_pattern = "THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES"

    relevant_text = ""
    for page_text in text_per_page:
        start_index = page_text.find(start_pattern)
        if start_index != -1:
            end_index = page_text.find(end_pattern, start_index)
            if end_index != -1:
                relevant_text += page_text[start_index:end_index]
            else:
                relevant_text += page_text[start_index:]
    return relevant_text

if __name__ == "__main__":
    
    extracted_text = extract_text_from_pdf(pdf_path)
    relevant_text = extract_units_of_dental_activity(extracted_text)
    print(relevant_text.strip())

Units of Dental Activity per Performer
111111 A BCDEFG
Current Financial Year 2018/19  351.60
Last Financial Year 2017/18  0.00
Other Financial Years  0.00
222222 B CDEFGH
Current Financial Year 2018/19  108.60
Last Financial Year 2017/18  0.00
Other Financial Years  0.00
333333  C DEFGHI
Current Financial Year 2018/19  394.40
Last Financial Year 2017/18  0.00
Other Financial Years  0.00

In [2445]:
import pandas as pd
import PyPDF2
import re

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_units_of_dental_activity(text_per_page):
    start_pattern = "Units of Dental Activity per Performer"
    end_pattern = "THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES"

    relevant_text = ""
    for page_text in text_per_page:
        start_index = page_text.find(start_pattern)
        if start_index != -1:
            end_index = page_text.find(end_pattern, start_index)
            if end_index != -1:
                relevant_text += page_text[start_index:end_index]
            else:
                relevant_text += page_text[start_index:]
    return relevant_text

def parse_performers(text):
    performer_data = re.findall(r'\b(\d+)\s+([A-Za-z\s]+)\s+Current', text)
    performer_ids, performer_names = zip(*performer_data)
    return performer_ids, performer_names

def extract_current_financial_year_rows(text, pattern, year_col_name, amount_col_name):
    current_year_rows = []
    lines = text.strip().split('\n')
    for line in lines:
        match = re.search(pattern, line)
        if match:
            year = match.group(1) if match.group(1) else '0'  # If year is missing, consider it as '0'
            current_year_rows.append({year_col_name: year, amount_col_name: match.group(2)})
    return current_year_rows

if __name__ == "__main__":
   
    
    # Extract text from PDF
    extracted_text = extract_text_from_pdf(pdf_path)
    
    # Extract relevant dental activity units
    relevant_text = extract_units_of_dental_activity(extracted_text)
    
    # Parse performer data
    performer_ids, performer_names = parse_performers(relevant_text)
    
    # Create performer DataFrame
    df_performers = pd.DataFrame({'Contract_ID': Contract_ID,'Statement_Reference':statement_reference,'Performer_ID': performer_ids, 'Name': performer_names})
    
    # Extract financial year rows
    current_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Current Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Current_Financial_Year', 
                                                            'Current_Financial_Year_Amount')
    
    last_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Last Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Last_Financial_Year', 
                                                            'Last_Financial_Year_Amount')

    other_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Other Financial Years(?: (\d{4}/\d{2}))?\s+([\d.]+)',
                                                            'Other_Financial_Years', 
                                                            'Other_Financial_Year_Amount')

    # Create financial year DataFrames
    df_current = pd.DataFrame(current_year_rows)
    df_last = pd.DataFrame(last_year_rows)
    df_other = pd.DataFrame(other_year_rows)
    
    # Concatenate financial year DataFrames
    df_financial_years = pd.concat([df_current, df_last, df_other], axis=1)
    
    # Print combined DataFrame
    combined_df = pd.concat([df_performers, df_financial_years], axis=1)
    df4 =combined_df

In [2446]:
df4

,Contract_ID,Statement_Reference,Performer_ID,Name,Current_Financial_Year,Current_Financial_Year_Amount,Last_Financial_Year,Last_Financial_Year_Amount,Other_Financial_Years,Other_Financial_Year_Amount
0,QRV 3954630008,1819/05,111111,A BCDEFG,2018/19,351.60,2017/18,0.00,0,0.00
1,QRV 3954630008,1819/05,222222,B CDEFGH,2018/19,108.60,2017/18,0.00,0,0.00
2,QRV 3954630008,1819/05,333333,C DEFGHI,2018/19,394.40,2017/18,0.00,0,0.00

In [2447]:
import pandas as pd
import sqlite3

# Assuming you have a DataFrame named df1

# Connect to SQLite database
conn = sqlite3.connect('compass.db')

# Assuming your table name is 'your_table_name'
table_name = 'Units_of_Dental_Activity_per_Performer'

# Insert DataFrame records into SQLite database
df4.to_sql(table_name, conn, if_exists='append', index=False)

# Commit changes and close connection
conn.commit()
conn.close()